Touchless Interactive: CSCI4970-Touchless-Interactive-Game/WebCamFunc.js File Reference
WebCamFunc.js File Reference
Functions
function loop ()
function switchDisplay (pixels)
function copyImageData (srcPixels, dstPixels, width, height)
function displaySpiral (pixels)
function displayWave (pixels)
function displayUpsideDown (pixels)
function displayPixelate (pixels, scaleFactor)
function displayGreyScreen (pixels)
function backgroundRemoval (pixels)
function displayMirror (pixels)
if (navigator.mediaDevices.getUserMedia)
window requestAnimationFrame (loop, canvas)
Variables
let video = document.createElement("video")
video autoplay = true
let canvas
let track = null
let settings = null
let tempCanvas = document.createElement("canvas")
let tempCtx = tempCanvas.getContext("2d")
let secondCanvas = document.createElement("canvas")
let secondCtx = secondCanvas.getContext("2d")
Function Documentation
backgroundRemoval()
function backgroundRemoval (pixels)
Method utilized to alter the pixel in order to create a background effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
copyImageData()
function copyImageData (srcPixels, dstPixels, width, height)
Method utilized to copy image data into another potentially blank image data object
Parameters
{ImageData.data} srcPixels the source of the image data to be copied
{ImageData.data} dstPixels the destination where the copied image data will be stored
{int} width the maximum width of pixel to be copied
{int} height the maximum height of the pixel to be copied
Referenced by displaySpiral(), and displayWave().
displayGreyScreen()
function displayGreyScreen (pixels)
Method utilized to alter the pixel in order to create a grey effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
displayMirror()
function displayMirror (pixels)
Method utilized to alter the pixel in order to create a mirror effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
displayPixelate()
function displayPixelate (pixels, scaleFactor)
Method utilized to alter the pixel in order to create a pixelate effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
{int} scaleFactor the int that represents how much will be max pixels to be scaled
References canvas, loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
displaySpiral()
function displaySpiral (pixels)
Method utilized to alter the pixel in order to create a spiral effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, copyImageData(), loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
displayUpsideDown()
function displayUpsideDown (pixels)
Method utilized to alter the pixel in order to create a upside down effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, loop(), secondCanvas, and secondCtx.
Referenced by switchDisplay().
displayWave()
function displayWave (pixels)
Method utilized to alter the pixel in order to create a wave effect based on the image data passed in
Parameters
{ImageData} pixels the image data that represents the current frame displayed
References canvas, copyImageData(), loop(), secondCanvas, secondCtx, settings, and tempCtx.
Referenced by switchDisplay().
if()
if (navigator.mediaDevices. getUserMedia)
References video.
loop()
function loop ()
Main method utilized to loop over the different effects
References canvas, loop(), secondCanvas, settings, switchDisplay(), tempCanvas, tempCtx, track, and video.
Referenced by backgroundRemoval(), displayGreyScreen(), displayMirror(), displayPixelate(), displaySpiral(), displayUpsideDown(), displayWave(), loop(), and switchDisplay().
requestAnimationFrame()
window requestAnimationFrame (loop , canvas)
switchDisplay()
function switchDisplay (pixels)
Method utilize as a main router for which effect to be displayed in the next frame
Parameters
{ImageData} pixels the image data that consist of the current frame that's displayed
References backgroundRemoval(), canvas, displayGreyScreen(), displayMirror(), displayPixelate(), displaySpiral(), displayUpsideDown(), displayWave(), and loop().
Referenced by loop().
Variable Documentation
autoplay
video autoplay = true
canvas
let canvas
Initial value:
= document.querySelector("#canvas")
let ctx = canvas.getContext("2d")
The canvas element that serves the purpose of controlling the canvas declared within the html
Referenced by backgroundRemoval(), displayGreyScreen(), displayMirror(), displayPixelate(), displaySpiral(), displayUpsideDown(), displayWave(), loop(), and switchDisplay().
secondCanvas
let secondCanvas = document.createElement("canvas")
A canvas element where the alternative image will be drawn into
Referenced by backgroundRemoval(), displayGreyScreen(), displayMirror(), displayPixelate(), displaySpiral(), displayUpsideDown(), displayWave(), and loop().
secondCtx
let secondCtx = secondCanvas.getContext("2d")
A context element where the alternative image will be drawn into
Referenced by backgroundRemoval(), displayGreyScreen(), displayMirror(), displayPixelate(), displaySpiral(), displayUpsideDown(), and displayWave().
settings
let settings = null
The settings that's contain within the video element
Referenced by displayWave(), and loop().
tempCanvas
let tempCanvas = document.createElement("canvas")
A temporary canvas where the each unalternative frame will be store and drawn
Referenced by loop().
tempCtx
let tempCtx = tempCanvas.getContext("2d")
A temporary context that belongs to the temporary canvas
Referenced by displayWave(), and loop().
track
let track = null
Track element that represent the video source from the video element
Referenced by loop().
video
let video = document.createElement("video")
The video element that serves the purpose of receving the input through webcam
Referenced by if(), and loop().